### ISSUE TITLE
Support Many to Many relationship

### ISSUE THREAD

**Issue by petkopara** [petkopara/TritonCrudBundle#7]

**Comment by raylight75** [comment]
А има ли за OnetoOne, OnetoMany, съжалявам за въпроса но просто нямам време да тествам точно сега. Смисъл ако има в еntitty -то onetoone в анотацията ще го генерира или..

**Comment by petkopara** [comment]
Здравей,
Да подържа OneToMany и OneToOne във формата, както и във филтрацията.
Засега няма подръжка на ManyToMany
https://github.com/petkopara/TritonCrudBundle/issues/7 .

2016-09-08 16:58 GMT+03:00 raylight75 <notifications@github.com>:

**Comment by raylight75** [comment]
Да тествах работят обаче има някакъв бъг, полето в което е декларирано чрез анатоция че ще има reletion не се визуализира - смисъл има го в edit но не и в show и index, ако го добавя на ръка работи но не се генерира автоматично. Не знам може и аз да бъркам нещо.

**Comment by petkopara** [comment]
Еми сигурно Sensio генерататора не го подържа, нали го extend-вам и затова
е така.
Обаче винаги може да отвориш request за този feature в issues и ще го
погледна като има време.

2016-09-09 14:31 GMT+03:00 raylight75 <notifications@github.com>:

**Comment by petkopara** [comment]
Introduced relation support of all doctrine relation types
